IPN_ENABLE_CREATE: true
IPN_USE_MANUFACTURER_PART_NUMBER: false
IPN_PREFIX: null
IPN_CATEGORY_CODE: true
IPN_UNIQUE_ID_LENGTH: '6'
IPN_ENABLE_PREFIX: false
IPN_ENABLE_SUFFIX: true
IPN_SUFFIX: '00'
INVENTREE_DEFAULT_REV: 'A'